# Configuration for Alacritty, the GPU enhanced terminal emulator.

live_config_reload: true

# import the current color theme
import:
  - ~/.config/alacritty/theme.yml

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: 'Fira Code'
    # family: 'Droid Sans Mono'
    # family: Hack

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Point size
  #size: 11.0
